### ISSUE TITLE
MC-Dropout during inference

### ISSUE THREAD

**Issue by valebi** [danielray54/DeepPulse#1]
Hi @danielray54 

Thanks for publishing the code alongside this cool paper - the reported results are amazing! 
Trying to reproduce the MAEs I'm a bit unsure about MC-dropout during inference. 

What I'm doing currently is just predicting 10 times and then taking the average. Am I on the right track?

I don't get the desired results though - the results are only slightly better than what gets printed under "Eval Mean" in the training notebook. 

I would be very grateful if you could help me out there, share some insights, or maybe even code if you don't mind.

Cheers & Thanks in advance
Valentin

**Comment by danielray54** [comment]
Hi Valentin,

Thank you for taking interest in my work.

Yes, you're on the right track - you do several forward passes to get samples from the predictive distribution. The number of samples is still a work in progress but from what I've read 25-30 should suffice. 

The MAE results in the paper are an average of the forward passes as well as an average of the LOSO folds. 

Just to note, this paper is a conference paper and not a complete body of work. I have made several improvements to this method and will publish a full form paper with a dataset I'm collecting at the moment. 

Finally, due to the stochastic nature of Deep Learning methods reproducing the exact same results is tricky.  When I carry out the full form paper I will repeat the whole process several times. 

More than happy to help further if you need.

Best,
Daniel

**Comment by valebi** [comment]
Hi Daniel

Thanks for the quick answer, that makes sense to me.
Did I understand correctly that you average the predictions of all models - even models that trained on the test sequence itself? That would surely resolve my issue of the higher MAE.

Best,
Valentin

**Comment by danielray54** [comment]
Hi Valentin,

Yes you are correct.

I have issues with this averaging as it doesn't reflect the generalisability of the method.

In my upcoming papers I will produce two MAE metrics: one as described above and a generalised MAE which is the test session only. 

Hopefully this will be made standard moving forward to compare the generalisability of methods. 

Thanks for making me aware this repo isn't complete - I will update it ASAP.

Best,
Daniel

**Comment by danielray54** [comment]
@
