### ISSUE TITLE
Architecture Compatibility

### ISSUE THREAD

**Issue by gunsodo** [danielray54/DeepPulse#1]
Thank you for sharing the implementation. Our team is interested in your architecture proposal so we are trying to reproduce the results with some other datasets. We notice some differences when we refer to the architecture diagram shown in the manuscript and the `DeepPulse.ipynb` file.

| Location | Paper | Implementation |
| --- | --- | --- |
| Conv Block | With dropout layer | Without dropout layer |
| Conv-MaxPool Block | Max pooling | Average pooling |
| Sensor-Specific Module  | 2 Conv-MaxPool blocks  | 1 Conv block + 1 Conv-MaxPool block |
| Bi-LSTM Layer  | Without layer normalization | With layer normalization |
| Prediction Module | Convolutional layer + ReLU + Dense | Only dense layer |

May I ask which implementation we should follow? Please let me know if I have overlooked any clarification. 

Also, if we should follow the paper, what would be the parameters for the last 1D convolutional layer in the prediction module? Should we insert another `Flatten` layer between that convolutional layer and the `Dense` layer as well?

**Comment by danielray54** [comment]
Hi, 

Thanks for taking interest in the project. 

Since writing the paper, I have been optimising the architecture and the one in the .ipynb file is the most accurate I found, the error rates are half of that of the paper implementation. 

I believe it would be best to follow this implementation as it adheres to the general architectural idea in the paper with some tweaks to improve accuracy.

Please let me know if you have any other queries. 

Thanks again for your interest.

**Comment by gunsodo** [comment]
Thank you very much for your answer. Congratulations once again on your publication!
