### ISSUE TITLE
Understanding code better

### ISSUE THREAD

**Issue by hamsade-google** [danielray54/DeepPulse#2]
Hi. Thanks so much for this awesome repo. The following lines are just getting the final later params as they are overwriting `distribution_params`, right?

`for i in x:
                distribution_params = []
                for item in i:
                    distribution_params.append(float(item))`

**Comment by danielray54** [comment]
Hi,

Thanks for taking intrest in my work. 
I have just had a look at the code you flagged and have now changed it as its rather unreadable and long-winded.

### Old code:
`x= model_deeppulse.predict([np.expand_dims(row["PPG"], axis=0), 
                                         np.expand_dims(row["ACC"], axis=0)],
                                        verbose=0)` 

- Here x is a list of lists with one list containing two values, e.g. `x = [[96.18737 70.89351]]`. The idea of the next bit of code is to make it a 1D list of floats to be inputted into the distribution function.

`for i in x:
  distribution_params = []
  for item in i:
      distribution_params.append(float(item))`

- Because there is only one item in the list of lists the distribution_params list isnt overwritten, so the output is:
`distribution_params = [96.18737030029297, 70.89350891113281]`

### New code:
Instead of using the previous code, a much more readable way would be:
`output = [float(i) for i in x[0]]`
which gives:
`output = [96.18737030029297, 70.89350891113281]`

Thanks again for flagging this, it seems I must have been sleep deprived when writing that bit of code.
